name: Deploy the worker


on:
  # Runs on a push
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
