name: Continuous testing


on:
  # Runs on a pull request
  pull_request:
    branches:
      - main


# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Run tests
        uses: cloudflare/wrangler-action@v3
        with:
          command: deploy --dry-run


  test-install-script:
    name: Test install script (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Run install script (brew)
        if: matrix.os == 'macos-latest'
        run: ./src/getomni.sh -B

      - name: Run install script (download)
        run: ./src/getomni.sh -D


  lint-install-script:
    name: Lint install script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Lint install script (sh)
        run: shellcheck -s sh src/getomni.sh

      - name: Lint install script (busybox)
        run: shellcheck -s busybox src/getomni.sh


  auto-merge:
    name: Auto-merge Dependabot pull-requests

    runs-on: ubuntu-latest

    needs:
      - tests
      - test-install-script
      - lint-install-script

    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'

    permissions:
      contents: none

    steps:
      - name: Automerge if Dependabot
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          command: 'squash and merge'
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
